create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null check (category in ('Кроссовки','Одежда','Аксессуары','Техника')),
  color text not null default '',
  price integer not null check (price > 0),
  status text not null check (status in ('В наличии','Под заказ')),
  delivery text not null default '10–17 дней',
  image text not null,
  sizes text[] not null default '{}',
  description text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  telegram text not null,
  city text not null,
  comment text not null default '',
  items jsonb not null,
  total integer not null default 0,
  status text not null default 'new',
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;
alter table public.orders enable row level security;

-- The application uses SUPABASE_SERVICE_ROLE_KEY only on the server.
-- Do not expose that key in NEXT_PUBLIC_* variables.

insert into public.products (id,name,category,color,price,status,delivery,image,sizes,description)
values
  (1,'New Balance 530','Кроссовки','White / Silver',9000,'Под заказ','10–17 дней','https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&w=1200&q=88',array['37','38','39','40','41','42','43'],'Лёгкая повседневная модель с фирменной амортизацией и серебристыми деталями.'),
  (2,'Nike Air Force 1','Кроссовки','Triple White',11000,'В наличии','1–3 дня','https://images.unsplash.com/photo-1600269452121-4f2416e55c28?auto=format&fit=crop&w=1200&q=88',array['38','39','40','41','42','43','44'],'Классические белые кроссовки из натуральной кожи. Проверка подлинности включена.'),
  (3,'ASICS Gel-Kayano 14','Кроссовки','Cream / Black',14900,'Под заказ','10–17 дней','https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=1200&q=88',array['37.5','38','39','40','41.5','42.5','43.5'],'Технологичная беговая эстетика 2000-х с мягкой посадкой и стабильной подошвой.'),
  (4,'Adidas Campus 00s','Кроссовки','Core Black',10500,'В наличии','1–3 дня','https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?auto=format&fit=crop&w=1200&q=88',array['37','38','39','40','41','42','43','44'],'Замшевый силуэт с объёмными шнурками и массивной подошвой в стиле 2000-х.')
on conflict (id) do nothing;

select setval(pg_get_serial_sequence('public.products','id'), greatest((select coalesce(max(id),1) from public.products),1));
