'use client'
import {useMemo,useState} from'react'
import{ArrowRight,CheckCircle2,Heart,Home,Minus,Plus,Search,ShoppingBag,ShoppingCart,SlidersHorizontal,Sparkles,Trash2,UserRound,X}from'lucide-react'

type View='Главная'|'Каталог'|'Избранное'|'Корзина'
type Product={id:number;name:string;color:string;price:number;image:string;sizes:string[]}
type CartItem={product:Product;size:string;quantity:number}

const products:Product[]=[
{id:1,name:'New Balance 530',color:'White / Silver',price:9000,image:'https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&w=1400&q=90',sizes:['37','38','39','40','41','42','43']},
{id:2,name:'Nike Air Force 1 Low White',color:'Triple White',price:11000,image:'https://images.unsplash.com/photo-1600269452121-4f2416e55c28?auto=format&fit=crop&w=1400&q=90',sizes:['38','39','40','41','42','43','44']},
{id:3,name:'Nike Air Force 1 Low Black',color:'Triple Black',price:11000,image:'https://images.unsplash.com/photo-1552346154-21d32810aba3?auto=format&fit=crop&w=1400&q=90',sizes:['38','39','40','41','42','43','44']}
]
const categoryImages=[
['Кроссовки','https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1200&q=85'],
['Одежда','https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=1200&q=85'],
['Аксессуары','https://images.unsplash.com/photo-1523779917675-b6ed3a42a561?auto=format&fit=crop&w=1200&q=85'],
['Техника','https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&w=1200&q=85']
]
const format=(n:number)=>`${n.toLocaleString('ru-RU')} ₽`

export default function InnerStore(){
const[view,setView]=useState<View>('Главная'),[query,setQuery]=useState(''),[favorites,setFavorites]=useState<number[]>([]),[selected,setSelected]=useState<Product|null>(null),[size,setSize]=useState(''),[cart,setCart]=useState<CartItem[]>([])
const shown=useMemo(()=>{let list=view==='Избранное'?products.filter(p=>favorites.includes(p.id)):products;const q=query.trim().toLowerCase();return q?list.filter(p=>(p.name+' '+p.color).toLowerCase().includes(q)):list},[view,query,favorites])
const count=cart.reduce((s,i)=>s+i.quantity,0),total=cart.reduce((s,i)=>s+i.product.price*i.quantity,0)
const toggle=(id:number)=>setFavorites(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id])
const open=(p:Product)=>{setSelected(p);setSize(p.sizes[0])}
const add=()=>{if(!selected||!size)return;setCart(v=>{const i=v.findIndex(x=>x.product.id===selected.id&&x.size===size);if(i<0)return[...v,{product:selected,size,quantity:1}];return v.map((x,n)=>n===i?{...x,quantity:x.quantity+1}:x)});setSelected(null);setView('Корзина')}
const quantity=(i:number,d:number)=>setCart(v=>v.flatMap((x,n)=>n!==i?[x]:x.quantity+d>0?[{...x,quantity:x.quantity+d}]:[]))
const cards=(list:Product[])=><div className="product-grid">{list.map(p=><article className="product-card" key={p.id} onClick={()=>open(p)}><div className="product-image-wrap"><span className="product-badge">ORIGINAL</span><button className={`favorite-button ${favorites.includes(p.id)?'is-active':''}`} onClick={e=>{e.stopPropagation();toggle(p.id)}}><Heart size={18} fill={favorites.includes(p.id)?'currentColor':'none'}/></button><img src={p.image} alt={p.name}/></div><div className="product-info"><h3>{p.name}</h3><p>{p.color}</p><strong>{format(p.price)}</strong><div className="product-meta"><span className="in-stock">В наличии</span><span>Оригинал. Проверено INNER.</span></div><button className="want-button" onClick={e=>{e.stopPropagation();open(p)}}>Хочу такие <ArrowRight size={16}/></button></div></article>)}</div>
return <main className="inner-app-shell"><div className="ice-orb ice-orb-one"/><div className="ice-orb ice-orb-two"/><div className="inner-app"><header className="topbar"><button className="brand-lockup" onClick={()=>setView('Главная')}><span className="brand-mark">IN</span><span className="brand-name">INNER</span></button><div className="topbar-actions"><button className="icon-button" onClick={()=>setView('Избранное')}><Heart size={20}/>{favorites.length>0&&<span className="counter">{favorites.length}</span>}</button><button className="icon-button" onClick={()=>setView('Корзина')}><ShoppingBag size={20}/>{count>0&&<span className="counter">{count}</span>}</button><button className="avatar-button"><UserRound size={18}/></button></div></header>{view!=='Корзина'&&<section className="search-row"><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Найти бренд или модель"/><button className="filter-button"><SlidersHorizontal size={18}/></button></section>}
{view==='Главная'&&<><section className="hero-card"><div className="hero-copy"><div className="eyebrow"><Sparkles size={14}/> ORIGINAL GOODS</div><h1>Оригинальные вещи без сложностей</h1><p>Оригинал без лишнего шума. Понятная цена. Чистая подача.</p><button className="primary-button" onClick={()=>setView('Каталог')}>Смотреть каталог <ArrowRight size={18}/></button></div><div className="hero-product"><div className="hero-glow"/><img src={products[0].image} alt="New Balance 530 на ледяном фоне"/><span className="original-stamp">100% ORIGINAL</span></div></section><section className="trust-strip"><div><CheckCircle2 size={18}/><span>Найдено. Проверено. Отправлено.</span></div><div><CheckCircle2 size={18}/><span>Понятная цена</span></div><div><CheckCircle2 size={18}/><span>Доставка по России</span></div></section><section className="section-block"><div className="section-heading"><div><span className="section-kicker">SHOP BY</span><h2>Категории</h2></div><button onClick={()=>setView('Каталог')}>Все <ArrowRight size={16}/></button></div><div className="category-grid">{categoryImages.map(([name,img],i)=><button className="category-card" key={name} onClick={()=>setView('Каталог')} style={{backgroundImage:`linear-gradient(180deg,rgba(5,9,14,.30),rgba(5,9,14,.92)),url(${img})`}}><span className="category-index">0{i+1}</span><span className="category-title">{name}</span><span className="category-count">Подборка INNER</span><ArrowRight className="category-arrow" size={18}/></button>)}</div></section><section className="section-block product-section"><div className="section-heading"><div><span className="section-kicker">CURATED</span><h2>Найдено для тебя</h2></div><button onClick={()=>setView('Каталог')}>Каталог <ArrowRight size={16}/></button></div>{cards(shown)}</section></>}
{(view==='Каталог'||view==='Избранное')&&<section className="catalog-page"><div className="page-header"><div><span className="section-kicker">INNER SELECT</span><h1>{view}</h1><p>{view==='Избранное'?'Сохранённые товары':'Оригинальные товары в наличии'}</p></div><span>{shown.length} товаров</span></div>{view==='Каталог'&&<div className="chips">{['Все','Кроссовки','Одежда','Аксессуары','Техника'].map((x,i)=><button className={i===0?'active':''} key={x}>{x}</button>)}</div>}{shown.length?cards(shown):<div className="empty-state"><Heart size={30}/><h3>Здесь пока пусто</h3><p>Добавьте товары в избранное.</p></div>}</section>}
{view==='Корзина'&&<section className="cart-page"><div className="page-header"><div><span className="section-kicker">YOUR ORDER</span><h1>Корзина</h1><p>{count?`${count} товара в заказе`:'Добавьте товар из каталога'}</p></div></div>{cart.length===0?<div className="empty-state"><ShoppingCart size={30}/><h3>Корзина пуста</h3><p>Выберите товар и размер.</p><button className="primary-button" onClick={()=>setView('Каталог')}>Перейти в каталог</button></div>:<div className="cart-layout"><div className="cart-list">{cart.map((i,n)=><article className="cart-item" key={`${i.product.id}-${i.size}`}><img src={i.product.image} alt={i.product.name}/><div><h3>{i.product.name}</h3><p>{i.product.color} · размер {i.size}</p><strong>{format(i.product.price)}</strong></div><div className="quantity"><button onClick={()=>quantity(n,-1)}>{i.quantity===1?<Trash2 size={16}/>:<Minus size={16}/>}</button><span>{i.quantity}</span><button onClick={()=>quantity(n,1)}><Plus size={16}/></button></div></article>)}</div><aside className="summary-card"><h2>Итого</h2><div><span>Товары</span><strong>{format(total)}</strong></div><hr/><div><span>К оплате</span><strong>{format(total)}</strong></div><a className="primary-button" href="https://t.me/lutoway" target="_blank">Оформить заявку</a></aside></div>}</section>}</div>
<nav className="bottom-nav">{([['Главная',Home],['Каталог',Search],['Избранное',Heart],['Корзина',ShoppingCart]] as const).map(([label,Icon])=><button key={label} className={view===label?'active':''} onClick={()=>setView(label)}><Icon size={20}/><span>{label}</span></button>)}</nav>
{selected&&<div className="overlay" onClick={()=>setSelected(null)}><section className="product-sheet" onClick={e=>e.stopPropagation()}><button className="close-button" onClick={()=>setSelected(null)}><X size={20}/></button><div className="detail-image"><img src={selected.image} alt={selected.name}/><span>ORIGINAL</span></div><div className="detail-content"><h2>{selected.name}</h2><p>{selected.color}</p><strong>{format(selected.price)}</strong><div className="delivery-row"><span className="in-stock">В наличии</span><span>Оригинал. Проверено INNER.</span></div><h3>Выберите размер</h3><div className="sizes">{selected.sizes.map(s=><button className={size===s?'active':''} onClick={()=>setSize(s)} key={s}>{s}</button>)}</div><button className="primary-button" onClick={add}>Хочу такие <ShoppingBag size={18}/></button></div></section></div>}</main>}
